cat <<EOF
window.VUE_APP_SERVICE_ENDPOINT="${VUE_APP_SERVICE_ENDPOINT}"
window.VUE_APP_IPFS_ENDPOINT="${VUE_APP_IPFS_ENDPOINT}"
window.VUE_APP_EXPLORER_ENDPOINT="${VUE_APP_EXPLORER_ENDPOINT}"
window.VUE_APP_TOTAL_ITEMS=${VUE_APP_TOTAL_ITEMS}
EOF